### ISSUE TITLE
TODO list for 0.1.0

### ISSUE THREAD

**Issue by xen0n** [loongson-community/loongarch-rs#1]
* [ ] `loongarch-insn-format` for data structures (is this necessary from the beginning?)
* [ ] `loongarch-insn` for instruction encodings
    - this should ideally be `no-std` so it could be leveraged in a future system-level `larva`
* [ ] `loongarch-opcode-def` for parsing `loongarch-opcodes` tables in Rust
    - this need not be `no-std`
